title: Mallikarjuna Manne
logo: /assets/img/logo1.jpg

description:
  <p align="center">
  <a href="pdf/Resume_Mallikarjuna.docx">Resume</a> |
  <a href="https://www.linkedin.com/in/mallikarjuna-manne-45706ba5/">LinkedIn</a> |
  <a href="https://github.com/mallikarjuna-manne">GitHub</a>
  
  <br>   
  Experienced Data Scientist in System Analysis, Machine learning, Deep learning, Data Cleaning, and Data Pre-processing. 
  Strong comprehension knowledge of systems, Passionate about Data science and technology. 
  Experienced in Computer Vision and NLP. Flexible to Learn New technologies and Apply in Projects.
  <br>
  </p>



theme: jekyll-theme-minimal
